name: inventerization_4aas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  mysql_client: ^0.0.27
  http: ^1.2.0
  auto_route: ^8.1.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  dio: ^5.8.0
  json_annotation: ^4.9.0
  mobile_scanner: ^4.0.0
  flutter_local_notifications: ^19.3.1
  windows_notification: ^1.3.0
  get_it: ^8.0.3
  network_info_plus: ^6.1.4
  permission_handler: ^11.3.0
  flutter_launcher_icons: ^0.14.4
  excel: ^4.0.6
  intl: ^0.20.2
  flutter_file_dialog: ^3.0.1
  window_manager: ^0.5.1
  file_picker: ^10.2.0

flutter_launcher_icons:
  android: "ic_launcher"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 
  image_path: "assets/icon.png" 

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
